### PR TITLE
Feat: one container to rule them all

### LINKED ISSUE #199: Execute Release Process with JDK11
### Feature Request

- JDK11 should be the default JDK used to execute the release process
  - As for today, we are using the latest OpenJDK8 available in the official Maven Docker Image: https://github.com/jenkins-infra/release/blob/833c03a28a04e8179b425bf4352259b5ba870ec7/PodTemplates.d/release-linux.yaml#L36

- The image [`jenkinsciinfra/docker-packaging:2.0.0`](https://github.com/jenkins-infra/docker-packaging/releases/tag/2.0.0) uses Adoptium (temuring) JDK11 so it should be used as base agent for release process

### PR DESCRIPTION
**Pull request by dduportal**
This PR introduces the following (major) changes to the release/packaging process for the weekly:

- ~#199 by using the `jenkinsciinfra/packaging:2.0.0` image, which uses JDK11 with Maven 3.8.4~ => updated to use https://github.com/jenkins-infra/docker-packaging/releases/tag/2.1.0 (with JDK8 by default). JDK11 will be a subsequent PR.
- Solves partially #201 by switching the Linux release process to "one JNLP container per pod)
- Nitpicks on the pod template file extension that weren't coherents

⚠️ This need to be tested, and the only way seems to wait for the next weekly release (and might need production live debugging)

### CODE REVIEW

**Review by timja — APPROVED** [review]

**Comment by daniel-beck** [comment]
Next week is security updates, please hold off merging.

**Comment by timja** [comment]
> Next week is security updates, please hold off merging.

Quite likely it will fail without this, we have network issues and this is the fix, Packaging failed many times and those fixes have been merged but this could fail with the same issue too.

**Comment by daniel-beck** [comment]
(GitHub is lacking the 😭 reaction)

**Comment by daniel-beck** [comment]
https://github.com/jenkins-infra/release/tree/security-stable-2.319.2 and https://github.com/jenkins-infra/release/tree/security-2.329 are the branches for next week, https://github.com/jenkins-infra/release/pulls/daniel-beck are PRs updating them with the correct security configuration. They will need to be updated with this change then.

CC @Wadeck looks like we're going to have an above average amount of fun next week…

**Comment by timja** [comment]
We could do an extra weekly..?

**Comment by timja** [comment]
> > We could do an extra weekly..? (to test this)
> 
> I vote for additional weekly to test the process and secure next week's sec release. I'm willing to take the additional required work if any for this.

just click merge here and trigger a release for now 😄 , feel free to do whenever

**Comment by daniel-beck** [comment]
Ideally this would be discussed with @Wadeck who will need to re-do the merges of security fixes we've already finished.

**Comment by timja** [comment]
Or stage security early?

**Comment by dduportal** [comment]
> Ideally this would be discussed with @Wadeck who will need to re-do the merges of security fixes we've already finished.

I've requested an advice to Wadeck internally. Let's see.

Please note that these "infra  PRs" does not have anything to do with the Jenkins code: it's only pipeline/pod code, and we will take part on the upcoming release process if need be to help

**Comment by daniel-beck** [comment]
> Please note that these "infra PRs" does not have anything to do with the Jenkins code

We've already prepared next week's content. If there's going to be an additional release between now and then, we need to re-do that to incorporate the changes published in the unscheduled weekly release (or we'd end up effectively undoing changes), plus update a bunch of documentation that would have the wrong version number. It's not _a lot_ but it's _some_; @Wadeck's plans for the release are ambitious and I'm off most of the time between now and then and therefore unable to assist a lot. He may well be fine with it, but IMO it'd be nice to at least check.

**Comment by timja** [comment]
AFAIU you generally do the staging a couple of days before actual release day? so can possibly just be tested then?

**Comment by daniel-beck** [comment]
Maven build and staging into Artifactory is done earlier. Packaging is done on the same day, as there's no staging environment for them. (Having a package staging environment has been an RFE from me from before Olivier started work on this repo…)

**Comment by timja** [comment]
> Maven build and staging into Artifactory is done earlier. Packaging is done on the same day, as there's no staging environment for them. (Having a package staging environment has been an RFE from me from before Olivier started work on this repo…)

Packaging was already tested, the only change to a packaging file in this PR is adding a file extension to a yaml file.

This PR is focused on the release flow

**Comment by dduportal** [comment]
Let's wait for Wadeck's feedback then. We now know the pros and cons of merging this PR. Thanks folks for the explanations

**Comment by dduportal** [comment]
Summary of the discussion with Wadeck:

- No test that would generate a weekly, because the changes since https://github.com/jenkinsci/jenkins/commit/8a304468476221b854166468cdc7e4b0ad2358ec could be time-wasting to backport (Wadeck/Daniel feedback)
- This PR hides another change: using JDK11 instead of JDK8 for the release generation. Even if it is a change to be done, it's risky (Damien feedback)
- The rest of the PR is not risky (pod single container) (feedback from all)

Proposal: 
- **Do not merge and try the release as it**: the release pipeline only allocate 1 pod and was succesful last tuesday because of the patch 1.13.2 of hte kubernetes plugin
- Infra team update this PR to ensure that JDK8 is used by maven (bump docker-packaging image from 2.0.0 to a 2.1.0).
- If the security release fails because of pods websockets, then we merge this PR (with JDK8) and retry immediatly with infra-team present
- The expected changes (One pod, JDK11, Windows, and maybe others) are expected for the next weekly AFTER the sec. release

**Comment by dduportal** [comment]
PR set as "draft" to protect from merging.

**Comment by dduportal** [comment]
Now, it's time to merge the dotnet Windows image with the Jenkins JNLP to ensure a single pod.

**Comment by dduportal** [comment]
THis PR is ready to be merged.

**Review by timja — APPROVED** [review]

**Pull request merged**
