### PR TITLE
Set deployAtEnd from maven-deploy-plugin

### PR DESCRIPTION
**Pull request by daniel-beck**
I think @jtnord explained that to me a while back?

https://maven.apache.org/plugins/maven-deploy-plugin/deploy-mojo.html#deployAtEnd

Untested. Might need to be put in `-Darguments`, unsure.

### CODE REVIEW

**Comment by olblak** [comment]
I haven't tested neither

**Comment by jtnord** [comment]
> I think @jtnord explained that to me a while back?

Probably.  If this works - would it not be better to put this into the pom?  that way a snapshot deployment and a release deployment will behave the same (or at least similar)?

**Comment by olblak** [comment]
> Probably. If this works - would it not be better to put this into the pom? that way a snapshot deployment and a release deployment will behave the same (or at least similar)?

While I like to have the same behavior everywhere in this case we use a different process so I am fine to leave this parameter defined here

**Comment by daniel-beck** [comment]
IMO it always makes sense to deployAtEnd, so it's a reasonable suggestion.

**Review by olblak — APPROVED** [review]

**Comment by lemeurherve** [comment]
How difficult it would be to put this in the pom?

**Pull request merged**
