### PR TITLE
feat(weekly) add new 2023 GPG key

### PR DESCRIPTION
**Pull request by dduportal**
Related to https://github.com/jenkins-infra/helpdesk/issues/3457

### CODE REVIEW

**Review by MarkEWaite — APPROVED** [review]
Thanks!

**Comment by MarkEWaite** [comment]
> LGTM, but I'd keep this PR on hold until tomorrow's release, allowing us a week to prepare announcements, instead of rushing everything today.

I'd rather rush it today, post the announcement today or tomorrow, and avoid the complaints that will arrive when the expired key is used March 31 - April 4.  If we don't implement until next weeks release, there will be several days when attempting to install the weekly release from RPM may fail due to the expired key.

**Review by timja — APPROVED** [review]

**Comment by MarkEWaite** [comment]
> I'd rather rush it today, post the announcement today or tomorrow, and avoid the complaints that will arrive when the expired key is used March 31 - April 4. If we don't implement until next weeks release, there will be several days when attempting to install the weekly release from RPM may fail due to the expired key.

Though I should be clear that since we're not creating a new LTS release, we can expect some complaints from LTS users that will be warned that the key has expired on the 2.387.1 release.  Will be resolved with the April 5, 2023 release of 2.387.2

**Comment by MarkEWaite** [comment]
https://github.com/jenkins-infra/jenkins.io/pull/6205 is the pull request that announces the change.  Needs additional changes in the install guide.

**Pull request merged**
