### PR TITLE
Switch to weekly release

### PR DESCRIPTION
**Pull request by olblak**
Once this pull request is merged and credentials updated, the release will be done directory to jenkinsci/jenkins on master branch and packages will be pushed to pkg.jenkins.io

- [x] ssh key is allowed to push commits to jenkinsci/jenkins 
- [x] releasebot is allowed to push artifacts to repo.jenkins-ci.org/releases
- [x] ssh key is allowed to push artifacts to pkg.jenkins.io
- [x] Trigger permission is restricted to three people [@oleg-nenashev, @daniel-beck, ? ]

Once all credentials are ready to be configured, I'll do one last reset of release.ci.jenkins.io

### CODE REVIEW

**Comment by olblak** [comment]
I updated the ldap group so only  @oleg-nenashev @daniel-beck  and I could trigger a release/packaging job, I am planning to remove myself once everything everthing is validated

**Comment by olblak** [comment]
I changed the releasebot credentials, but I didn't update release.ci.jenkins.io yet

**Comment by olblak** [comment]
I generated a new pair of ssh key, one to push commit to jenkinsci/jenkins and a second one to push artifacts to pkg.jenkins.io.

release.ci.jenkins.io hasn't be updated with new credentials yet

**Comment by daniel-beck** [comment]
> I updated the ldap group so only @oleg-nenashev @daniel-beck and I could trigger a release/packaging job, I am planning to remove myself once everything everthing is validated

Needs to include @olivergondza ( https://issues.jenkins-ci.org/secure/ViewProfile.jspa?name=olivergondza ) as he's the only one who regularly should do regular releases.

**Pull request merged**
