### PR TITLE
fix(release script) use the new staging repository layout maven when staging a release

### PR DESCRIPTION
**Pull request by dduportal**
Ref. https://github.com/jenkins-infra/helpdesk/issues/3143. (line edited at this PR does not fix any problem).

It ensures that the specified staging repository uses the new maven-deploy layout as per https://maven.apache.org/plugins/maven-deploy-plugin/#major-version-upgrade-to-version-3-0-0.

In order to merge PR, I need help by Maven expert to confirm that I'm not doing something crazy here.

Ping @basil @jglick @jnord @daniel-beck @timja @MarkEWaite you are my Maven experts 🍯 May I get your advise?

### CODE REVIEW

**Comment by dduportal** [comment]
🤔 https://github.com/jenkins-infra/helpdesk/issues/3143#issuecomment-1253895119

**Review by basil — APPROVED** [review]
> This PR fixes https://github.com/jenkins-infra/helpdesk/issues/3143.

No. See my subsequent comments in that ticket for analysis.

Maven Release Plugin 3.x is backward compatible with the older `-DstagingRepository` format, so while this change is positive in that it migrates us to the new format, it is not strictly necessary for correctness. Approving this based on the fact that the new format is preferred over the old format, and we are using Maven Release Plugin 3.x (which accepts the new format) on both the main branch and the `stable-2.361` branch. Note that if, for some reason, we had to downgrade Maven Release Plugin back to 2.x, we would also have to go back to the old format.

**Comment by dduportal** [comment]
I'm setting this PR as draft because of the following argument:

> Note that if, for some reason, we had to downgrade Maven Release Plugin back to 2.x, we would also have to go back to the old format.

Rationale is that we might need to revert the Maven release plugin to 2.x to unblock staging releases given the direction of https://github.com/jenkins-infra/helpdesk/issues/3143 .

**Comment by timja** [comment]
> Rationale is that we might need to revert the Maven release plugin to 2.x to unblock staging releases given the direction of https://github.com/jenkins-infra/helpdesk/issues/3143 .

If so just revert this PR?

The maintainers of Maven have said that format is deprecated and they will likely drop it in 4.x, they were quite resistant in even adding this backwards compatibility from looking at the issue.

**Comment by dduportal** [comment]
Sure. I've updated the PR, fixed conflicts, it's ready to be reviewed, approved and merged.

**Review by timja — APPROVED** [review]

**Pull request merged**
