### PR TITLE
Merge master branch into stable-2.361 for LTS 2.361.2 release

### PR DESCRIPTION
**Pull request by krisstern**
Prepare for LTS release of 2.361.2

### CODE REVIEW

**Comment by NotMyFault** [comment]
Is any of that change actually needed for the next point release?

**Comment by krisstern** [comment]
Thanks @NotMyFault for the correction! My apologies for overlooking the fact that this PR is not necessarily, as no backporting has been done in the `release` repository. Let me close this PR now.

**Comment by krisstern** [comment]
On second thought I think maybe we should backport at least some of the commits here.

**Comment by krisstern** [comment]
Just checked we don't actually really need any of the listed commits for the upcoming LTS release on October 5

**Pull request closed without merging**
